'use client';

import { Inter } from 'next/font/google';
import { useState, useEffect } from 'react';
import Header from '@/app/components/Header';
import Footer from '@/app/components/Footer';
import RulesInfo from '@/app/components/RulesInfo';
import StartButton from '@/app/components/ui/StartButton';
import WordsDesk from './components/ui/WordsDesk';
import Timer from '@/app/components/ui/Timer';
import SendField from '@/app/components/ui/SendField';
import Link from 'next/link';
import './globals.css';
import { timeEnd } from 'console';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [mode, setMode] = useState(false);
  const [words, setWords] = useState(['']);
  const [npc, setNpc] = useState(false);
  const [minutes, setMinutes] = useState(1);
  const [seconds, setSeconds] = useState(59);
  useEffect(() => {}, [npc, setNpc]);
  return (
    <html lang='ru'>
      <body className={`font-sans bg-grey-200 inline-flex justify-center items-center flex-grow`}>
        <div className=' min-h-fit pb-6 w-[576px] my-0 mx-auto max-w-xl bg-white rounded-2xl shadow'>
          <Header>
            {mode === false ? (
              <div className='flex p-4 border-b-2 border-zinc-100'>
                <h1 className='text-center'>Игра в города на время</h1>
              </div>
            ) : (
              <div className='flex p-4 border-b-4 border-violet-100'>
                <h1 className='mr-auto'>{npc === false ? 'Сейчас ваша очередь' : 'Сейчас очередь соперника'}</h1>
                <Timer minutes={minutes} setMinutes={setMinutes} seconds={seconds} setSeconds={setSeconds} />
              </div>
            )}
          </Header>
          <main className='flex'>{mode === false ? <RulesInfo /> : <WordsDesk words={words} />}</main>
          <Footer>
            {mode === false ? (
              <StartButton onClick={setMode} mode={mode} />
            ) : (
              <SendField
                words={words}
                onSubmit={setWords}
                queue={npc}
                queueSet={setNpc}
                minutes={minutes}
                setMinutes={setMinutes}
                seconds={seconds}
                setSeconds={setSeconds}
              />
            )}
          </Footer>
        </div>
      </body>
    </html>
  );
}
